// Final team points for the completed 2026 Pub Hunt, keyed by exact team
// name. Baked from the host-exported pubhunt-scores.csv (the "Total"
// column = clash + route quiz + photo + anagram + console + brain +
// missing-vowels + Facebook points). The per-team answer tables are
// admin-only (RLS), so this public leaderboard reads its points from this
// frozen snapshot, while team name, theme, captain and cover art load live
// from the same anon-readable sources the team login uses. To refresh after
// more marking, re-export from the Host dashboard and regenerate this map.

export const TEAM_POINTS: Record<string, number> = {
  'IAM a Plant, IAM a Zombie': 133,
  '50 Shades of Spray': 99,
  'The Clever Ones': 96,
  'FC Wild Cards': 95,
  'I am rubber, you are glue': 95,
  '2nd Best': 86,
  'No thoughts, only Potato': 86,
  'Zero Pucks Given': 86,
  'Chilled Out Chickens': 84,
  'Raiders of the lost packets': 84,
  'Cyber-drunk': 81,
  'Full Kit Bankers': 80,
  'My name Chef': 80,
  'S.T.A.R.S.': 79,
  'Data Ventures': 78,
  'Wreck it & Rollback': 78,
  'No Pain No Game': 77,
  'Cyber-Glitch-Hopper': 76,
  'Fruit Juice Ninjas': 76,
  'Compass': 75,
  'Wild Goose Chase!': 74,
  'The Mild Hunt': 72,
  'The Ultimate Warriors': 71,
  'Accidental TV Damage': 69,
  'The Swarm': 69,
  'Temu Hades': 68,
  'Woooo!!': 66,
  'We\'re just here to expense it': 64,
  'Billy\'s Mates': 63,
  'Random Encounter': 60,
  'Revenge of the Stakeholders': 60,
  'Stirrups R Us': 60,
  'Tony Hawk Pro Lenders': 59,
  'Green Machines': 56,
  'Saddle Sore Squad': 55,
  'Mortalled': 54,
  'Early Careers FC': 53,
  'Hook Funt': 52,
  'I like big putters and I cannot lie': 51,
  'Village Idiots': 51,
  'The Booze Lightyears': 49,
  'Crop It Like It\'s Hot': 48,
  'The Sackstreet Boys': 48,
  'Atomic Securities': 47,
  'Lost Toys': 46,
  'Wormageddon': 44,
  'Purn\'s Puppets': 40,
  'Bald and Beautiful': 39,
  'Grand Theft Ale': 39,
  'Here for Beer': 36,
  'Cheeky Pluckers': 32,
  'Skyrimmers': 31,
  'Clash of Pints': 30,
  'Kev Cochrane\'s Worn-out Joystick': 30,
  'Waka Waka, Work Harder': 25,
  'Game of Throws': 24,
  'Golden Pint Chasers': 22,
  'Sim & Tonic': 22,
  'Why has the rum gone?': 21,
  '3rd Vents the Charm': 17,
  'Oh, Behave!': 17,
  'Pubthumping': 17,
  'Hadouken on Tap': 15,
  'Only Gnomes': 12,
  'Ping-Pong': 12,
  'Chips and Salsa': 9,
  'Oh No!': 9,
  'The Hedgefund Managers': 9,
  'Pay, no pay': 8,
  'Kevin Costner Fan Club': 3,
  'Team Chundrake (It\'s Chunning Home)': 2,
  'Tetris': 0,
  'The NPC\'s': 0,
  'We are supposed to be a Unit !': 0,
};
